CREATE DATABASE IF NOT EXISTS blog;

USE blog;

CREATE TABLE IF NOT EXISTS posts(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	content VARCHAR(255) NOT NULL
);

INSERT INTO posts (content) VALUES ('The quick brown fox jumps over the lazy dog.');
INSERT INTO posts (content) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit.');
INSERT INTO posts (content) VALUES ('This is a test post with some sample content.');
INSERT INTO posts (content) VALUES ('Another day, another blog post.');
INSERT INTO posts (content) VALUES ('Just sharing my thoughts on this topic.');
INSERT INTO posts (content) VALUES ('Check out this interesting article I found.');
INSERT INTO posts (content) VALUES ('Feeling inspired to write something new today.');
INSERT INTO posts (content) VALUES ('What are your favorite hobbies?');
INSERT INTO posts (content) VALUES ('Let\'s discuss the latest news.');
INSERT INTO posts (content) VALUES ('Looking for recommendations for good books.');
INSERT INTO posts (content) VALUES ('The weather is beautiful today!');
INSERT INTO posts (content) VALUES ('Coding is my passion.');
INSERT INTO posts (content) VALUES ('Enjoying a cup of coffee and writing code.');
INSERT INTO posts (content) VALUES ('Learning new things every day.');
INSERT INTO posts (content) VALUES ('Stay positive and keep moving forward.');
INSERT INTO posts (content) VALUES ('Have a wonderful day!');
INSERT INTO posts (content) VALUES ('This is just a random thought.');
INSERT INTO posts (content) VALUES ('Sharing some positivity with you all.');
INSERT INTO posts (content) VALUES ('What are you working on right now?');
INSERT INTO posts (content) VALUES ('Let\'s connect and share ideas.');
INSERT INTO posts (content) VALUES ('The future is bright.');
INSERT INTO posts (content) VALUES ('Embrace the challenges and grow.');
INSERT INTO posts (content) VALUES ('Believe in yourself and your dreams.');
INSERT INTO posts (content) VALUES ('Making progress step by step.');
INSERT INTO posts (content) VALUES ('Small steps lead to big changes.');
INSERT INTO posts (content) VALUES ('Keep learning and keep growing.');
INSERT INTO posts (content) VALUES ('Never give up on your goals.');
INSERT INTO posts (content) VALUES ('You are capable of amazing things.');
INSERT INTO posts (content) VALUES ('Dream big and work hard.');
INSERT INTO posts (content) VALUES ('Success is a journey, not a destination.');
INSERT INTO posts (content) VALUES ('Every day is a new opportunity.');
INSERT INTO posts (content) VALUES ('Make the most of every moment.');
INSERT INTO posts (content) VALUES ('Live life to the fullest.');
INSERT INTO posts (content) VALUES ('Be kind and spread love.');
INSERT INTO posts (content) VALUES ('Help others and make a difference.');
INSERT INTO posts (content) VALUES ('The world needs more kindness.');
INSERT INTO posts (content) VALUES ('Let your light shine.');
INSERT INTO posts (content) VALUES ('Be the change you wish to see in the world.');
INSERT INTO posts (content) VALUES ('Together we can make a difference.');
INSERT INTO posts (content) VALUES ('Spread positivity and inspire others.');
INSERT INTO posts (content) VALUES ('Create a better future for all.');
INSERT INTO posts (content) VALUES ('Imagine the possibilities.');
INSERT INTO posts (content) VALUES ('The power of imagination is limitless.');
INSERT INTO posts (content) VALUES ('Think outside the box.');
INSERT INTO posts (content) VALUES ('Explore new horizons.');
INSERT INTO posts (content) VALUES ('Dare to be different.');
INSERT INTO posts (content) VALUES ('Challenge the status quo.');
INSERT INTO posts (content) VALUES ('Innovate and create.');
INSERT INTO posts (content) VALUES ('Make your mark on the world.');
INSERT INTO posts (content) VALUES ('Leave a legacy behind.');
INSERT INTO posts (content) VALUES ('Inspire generations to come.');
INSERT INTO posts (content) VALUES ('The journey of a thousand miles begins with a single step.');
INSERT INTO posts (content) VALUES ('Believe you can and you\'re halfway there.');
INSERT INTO posts (content) VALUES ('The only way to do great work is to love what you do.');
INSERT INTO posts (content) VALUES ('Strive not to be a success, but rather to be of value.');
INSERT INTO posts (content) VALUES ('The mind is everything. What you think you become.');
INSERT INTO posts (content) VALUES ('What you get by achieving your goals is not as important as what you become by achieving your goals.');
INSERT INTO posts (content) VALUES ('Happiness is not something ready made. It comes from your own actions.');
INSERT INTO posts (content) VALUES ('The best way to predict the future is to create it.');
INSERT INTO posts (content) VALUES ('It always seems impossible until it\'s done.');
INSERT INTO posts (content) VALUES ('Your time is limited, don\'t waste it living someone else\'s life.');
INSERT INTO posts (content) VALUES ('Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.');
INSERT INTO posts (content) VALUES ('The only limit to our realization of tomorrow will be our doubts of today.');
INSERT INTO posts (content) VALUES ('The purpose of life, after all, is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.');
INSERT INTO posts (content) VALUES ('Life is what happens when you\'re busy making other plans.');
INSERT INTO posts (content) VALUES ('Get busy living or get busy dying.');
INSERT INTO posts (content) VALUES ('You only live once, but if you do it right, once is enough.');
INSERT INTO posts (content) VALUES ('Many of life\'s failures are people who did not realize how close they were to success when they gave up.');
INSERT INTO posts (content) VALUES ('If you want to live a happy life, tie it to a goal, not to people or things.');
INSERT INTO posts (content) VALUES ('Not how long, but how well you have lived is the main thing.');
INSERT INTO posts (content) VALUES ('In order to write about life first you must live it.');
INSERT INTO posts (content) VALUES ('Turn your wounds into wisdom.');
INSERT INTO posts (content) VALUES ('The unexamined life is not worth living.');
INSERT INTO posts (content) VALUES ('Where there is love there is life.');
INSERT INTO posts (content) VALUES ('We are what we repeatedly do. Excellence, then, is not an act, but a habit.');
INSERT INTO posts (content) VALUES ('Let us always meet each other with smile, for the smile is the beginning of love.');
INSERT INTO posts (content) VALUES ('A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.');
INSERT INTO posts (content) VALUES ('The greatest glory in living lies not in never falling, but in rising every time we fall.');
INSERT INTO posts (content) VALUES ('Go confidently in the direction of your dreams. Live the life you\'ve imagined.');
INSERT INTO posts (content) VALUES ('May you live every day of your life.');
INSERT INTO posts (content) VALUES ('Life is really simple, but we insist on making it complicated.');
INSERT INTO posts (content) VALUES ('Don\'t cry because it\'s over, smile because it happened.');
INSERT INTO posts (content) VALUES ('Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.');
INSERT INTO posts (content) VALUES ('Do what you can, with what you have, where you are.');
INSERT INTO posts (content) VALUES ('Be the change that you wish to see in the world.');
INSERT INTO posts (content) VALUES ('Live as if you were to die tomorrow. Learn as if you were to live forever.');
INSERT INTO posts (content) VALUES ('We must let go of the life we have planned, so as to accept the one that is waiting for us.');
INSERT INTO posts (content) VALUES ('I have decided to stick with love. Hate is too great a burden to bear.');
INSERT INTO posts (content) VALUES ('The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.');
INSERT INTO posts (content) VALUES ('The only thing we have to fear is fear itself.');
INSERT INTO posts (content) VALUES ('It is during our darkest moments that we must focus to see the light.');
INSERT INTO posts (content) VALUES ('The journey not the arrival matters.');
INSERT INTO posts (content) VALUES ('The future belongs to those who believe in the beauty of their dreams.');
INSERT INTO posts (content) VALUES ('Everything you’ve ever wanted is on the other side of fear.');
INSERT INTO posts (content) VALUES ('Be yourself; everyone else is already taken.');
INSERT INTO posts (content) VALUES ('To live is the rarest thing in the world. Most people exist, that is all.');
INSERT INTO posts (content) VALUES ('Without music, life would be a mistake.');
INSERT INTO posts (content) VALUES ('We are all in the gutter, but some of us are looking at the stars.');
INSERT INTO posts (content) VALUES ('What is to give light must endure burning.');

SELECT * FROM posts;
